# Generated by Django 4.2.7 on 2025-12-03 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="newsarticle",
            new_name="news_newsar_publish_efb9f8_idx",
            old_name="news_newsar_publish_idx",
        ),
        migrations.RenameIndex(
            model_name="newsarticle",
            new_name="news_newsar_source_2a5eed_idx",
            old_name="news_newsar_source_idx",
        ),
    ]
